version: "3"

services:
  px4:
    build: .
    volumes:
      - ./px4_ros_com_ros2:/root/px4_ros_com_ros2
      - ./mavlink_router.conf:/etc/mavlink-router/main.conf
      - ./super_client_configuration_file.xml:/root/super_client_configuration_file.xml
    environment:
      - ROS2_MASTER_IP=192.168.2.122
      - FASTRTPS_DEFAULT_PROFILES_FILE=/root/super_client_configuration_file.xml
      - ROBOT_NAME=rover5
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    privileged: true
    tty: true
    network_mode: "host"
    # ports:
    #  - 14570:14570/udp
